global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'todo-backend'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
      action: keep
      regex: 'todo-app-backend'
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    metric_relabel_configs:
    - source_labels: [__name__]
      regex: '(.*)'
      action: keep

  - job_name: 'todo-frontend'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
      action: keep
      regex: 'todo-app-frontend'
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    metric_relabel_configs:
    - source_labels: [__name__]
      regex: '(.*)'
      action: keep

  - job_name: 'dapr'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_dapr_io_enabeled]
      action: keep
      regex: 'true'
    - source_labels: [__address__]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:9090
      target_label: __address__
    - source_labels: [__meta_kubernetes_pod_name]
      target_label: pod_name
    metric_relabel_configs:
    - source_labels: [__name__]
      regex: 'dapr_.*'
      action: keep

  - job_name: 'kafka'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
      action: keep
      regex: 'kafka.*|strimzi.*'
    - source_labels: [__address__]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:9308
      target_label: __address__
    metric_relabel_configs:
    - source_labels: [__name__]
      regex: 'kafka_.*|strimzi_.*'
      action: keep